spring:
  application:
    name: aggregation-service

clients:
  catalog:
    base-url: ${CLIENT_CATALOG_BASE_URL:http://localhost:8081}
  pricing:
    base-url: ${CLIENT_PRICING_BASE_URL:http://localhost:8082}
  availability:
    base-url: ${CLIENT_AVAILABILITY_BASE_URL:http://localhost:8083}
  customer:
    base-url: ${CLIENT_CUSTOMER_BASE_URL:http://localhost:8084}

